; Inno Setup Script for FileConverter
; Compiles the PyInstaller output into a professional Setup Installer wizard.

[Setup]
AppId={{C6F6F945-8B2E-4F36-8096-7D51CD77A142}
AppName=FileConverter
AppVersion=2.0.0
AppPublisher=FileConverter Contributors
AppPublisherURL=https://github.com/samilkeklikoglu/File_Converter
AppSupportURL=https://github.com/samilkeklikoglu/File_Converter/issues
AppUpdatesURL=https://github.com/samilkeklikoglu/File_Converter/releases
VersionInfoVersion=2.0.0.0
DefaultDirName={localappdata}\Programs\FileConverter
DefaultGroupName=FileConverter
UninstallDisplayIcon={app}\FileConverter.exe
SetupIconFile=assets\fileconverter.ico
PrivilegesRequired=lowest
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
WizardStyle=modern
Compression=lzma2
SolidCompression=yes
OutputDir=dist
OutputBaseFilename=FileConverter-2.0.0-Setup
DisableWelcomePage=no
LicenseFile=LICENSE

[Languages]
Name: "turkish"; MessagesFile: "compiler:Languages\Turkish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Source path points to the executable generated by PyInstaller
Source: "dist\FileConverter.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "LICENSE"; DestDir: "{app}"; DestName: "LICENSE.txt"; Flags: ignoreversion
Source: "THIRD_PARTY_NOTICES.md"; DestDir: "{app}"; Flags: ignoreversion
Source: "PRIVACY.md"; DestDir: "{app}"; Flags: ignoreversion
Source: "CHANGELOG.md"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{group}\FileConverter"; Filename: "{app}\FileConverter.exe"
Name: "{autodesktop}\FileConverter"; Filename: "{app}\FileConverter.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\FileConverter.exe"; Description: "{cm:LaunchProgram,FileConverter}"; Flags: nowait postinstall skipifsilent
